Improve build script to work from any directory

diff --git a/bin/obsidianc b/bin/obsidianc
--- a/bin/obsidianc
+++ b/bin/obsidianc
@@ -1,3 +1,22 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-java -jar target/scala-2.12/obsidianc.jar "$@" 
+bin_dir="$(cd "$(dirname $BASH_SOURCE)"; pwd)"
+root_dir="$bin_dir/.."
+export OBSIDIAN_COMPILER_DIR="$root_dir"
+
+obsidian_jar="$root_dir/target/scala-2.12/obsidianc.jar"
+
+if [[ ! -e "$obsidian_jar" ]]; then
+    (
+        cd "$root_dir"
+        sbt assembly
+    )
+
+    if [[ "$?" != "0" ]]; then
+        echo "Error building jar file, exiting."
+        exit 1
+    fi
+fi
+
+java -jar "$obsidian_jar" $@
+
